name:                Mute
license:             BSD3

dependencies:
- base >= 4.7 && < 5

executables:
  mute:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
    dependencies:
        - process

